name: Build Chess Engine

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        run: choco install mingw

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Run clang-format check
        run: |
          clang-format --version
          clang-format -i src/*.cpp include/*.h
          git diff --exit-code

      - name: Run clang-tidy check
        run: |
          cmake -G "MinGW Makefiles" -B build
          clang-tidy --version
          clang-tidy -p build src/*.cpp include/*.h

      - name: Build CMake
        run: cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chess_engine
          path: build/chess_engine.exe
