name: Build Chess Engine

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        run: choco install mingw

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Install clang-format and clang-tidy
        run: choco install llvm

      - name: Run clang-format check
        run: |
          clang-format --version
          clang-format -i src/**/*.cpp src/**/*.h
          git diff --exit-code

      - name: Run clang-tidy check
        run: |
          cmake -G "MinGW Makefiles" -B build
          clang-tidy --version
          clang-tidy -p build src/**/*.cpp include/**/*.h

      - name: Configure and Build CMake
        run: cmake -DASAN=OFF -DOPTIMIZE=ON -G "MinGW Makefiles" -B build && cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chess_engine
          path: build/chess_engine.exe
